### ISSUE TITLE
After latest update v2.0.0, all text is white

### ISSUE THREAD

**Issue by Blake-LeBlanc** [MaxGraey/atom-dark-fusion-syntax#8]
First off, I use your syntax theme every day, your attention to detail is superb! The way you did the little green dots for matching tags is so awesome :) 

![image](https://cloud.githubusercontent.com/assets/19244245/22037221/f3da23d8-dcbb-11e6-9e2e-0bfa66860371.png)

Things I've tried:

- Removing and reinstalling the package
- Removing /.atom/config.cson and allowing it to be rebuilt upon Atom's start
- Pairing with different UI themes
- Playing a round of golf

Things I haven't yet tried:
- Taking an extended vacation to some exotic location

If it's of any help, the other default syntax themes seem to be working okay. 
 
Atom version 1.12.2 (Linux)
Syntax theme version 2.0.0
Primarily Ruby language, so mostly .rb and html.erb files. Standard .html markup is also white.

If you need any more info or would like me to try something, please let me know, I'm happy to help!

**Comment by MaxGraey** [comment]
Hi, Spectator6 and my apologise! You use Atom version 1.12.2 which use shadowDOM and pseudo selectors which in turn actively used in syntax styles. Starting upon v1.13.0 Atom's developers decide [get ridding of shadow DOM](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html) and it has influenced the syntax theme for it. All selectors was rewrited for compatibility with latest Atom version. That's why this is **major update version (2.0.0)**.

So you have two solutions:
1. Update to Atom 0.13.0
2. Or still to use previous version of Dark Atom Fusion theme. You should reinstall it using following command for this case:
```apm install atom-dark-fusion-syntax@1.5.1```

**Comment by Blake-LeBlanc** [comment]
Updating to 0.13.0 did the trick, thank you for your quick reply Max! Back to using your great theme :)
